### ISSUE TITLE
How to run in wayland?

### ISSUE THREAD

**Issue by LeoIannacone** [evolve-os/budgie-desktop#103]
Hi..

is it compatible with wayland, and, in case, how to launch it?

**Comment by ZetaHunter** [comment]
Almost a year later now, I am wondering how is the Wayland support at this moment?

**Comment by ikeydoherty** [comment]
Again it's not yet a priority. Remember that Budgie's primary environment is Solus, and we can't ship it there for Wayland because there is no support in the proprietary GLX drivers for Wayland.
Also at this point I'm inclined to say "contributions welcome" - as developer support has completely dried up, leaving but one (me)

In the near future it is planned to rewrite Budgie, in a single-process model. To do that would involve a lot of effort, but would /enable/ Wayland compatibility. At the end of the day, Wayland is an enormous pain in the arse for me as it involves a complete rewrite, a totally new architecture, and no actual benefits for Solus. (We'd still need to default to X11 as Wayland just _isn't quite ready yet on the desktop_

**Comment by NuLogicSystems** [comment]
Wayland uses EGL and not GLX:
https://wayland.freedesktop.org/faq.html#heading_toc_j_12

**Comment by ikeydoherty** [comment]
Fully aware of that @NuLogicSystems - and generically the existing proprietary drivers are known as GLX drivers. Whether it's correct is besides the point, that's the known term for them.

**Comment by NuLogicSystems** [comment]
OK then, I've never heard of that but to each their own. ;)

**Comment by ikeydoherty** [comment]
Sorta like ATM Machine and all the other annoying-as-fuck things :P

**Comment by NuLogicSystems** [comment]
I just haven't heard of the Nvidia driver referred to in that way before.
When I think of GLX I think Silicon Graphics not Nvidia, that is all I meant.

I apologize if I annoyed you in some way.
AJSlye

AJSlye

**Comment by ikeydoherty** [comment]
Never said _you_ were annoying, just that those turns of phrase are generally annoying, along with examples like "ATM machine" :P "GLX Driver" isn't really valid at all, refers to the GLX implementation using in X.Org - when we all know that's only one part of the picture ^^
