### ISSUE TITLE
[Enhacement] Clicking on the Icon of an Item in Another Workspace Will Not Bring The Focus To That Workspace

### ISSUE THREAD

**Issue by Saroufim** [evolve-os/budgie-desktop#66]
Naturally, when you click on the icon of a window in another workspace, the window manager would immediately switch to that workspace to show you the window. Budgie-panel would only provoke a notification saying that the window is ready but will not bring the window forward. It would be nice if it would.

**Comment by ikeydoherty** [comment]
Unsure what to do with this one tbh. The applet you mention is only provided for a GNOME Panel compatibility mode, and uses the same library to achieve it (we don't control it)

Basically we can't fix it because its not ours :) That said better workspace management will be coming to Budgie soon enough..
